config/routes.rb
Rails.application.routes.draw do
  get "about" => "pages#about"
  root "pages#about"
  resources :projects
  resources :authors
  resources :author_sessions, only:[:new, :create, :destroy]
  resources :contacts, only: [:new, :create]
  get "login" => "author_sessions#new"
  get "logout" => "author_sessions#destroy"
end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "Should match confirmation",
  if: :password
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "My Contact Form",
      :to => "simon_somlai@hotmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "300x300>", large: "1000x1000>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg","image/jpeg","image/png","image/gif"] 
	has_attached_file :preview, styles: { medium: "1440x2560>"}
	validates_attachment_content_type :preview, :content_type => ["image/jpg", "image/png", "image/jpeg"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
	def new

	end

	def create
		if login(params[:email], params[:password])
			redirect_back_or_to root_path 
			flash[:notice] = "Logged In"
		else 
			flash.now.alert="Login Failed"
			render action :new
		end
	end

	def destroy
		logout
		redirect_to(:authors, notice: "Logged Out")
	end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  # Make Sure Only Admin Can Create New Users
  before_filter :admin
  def admin
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end
  


  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new 
		@contact = Contact.new
	end
	
	def create 
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = "Cannot send message"
			render :new
		end
	end 

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def about 

end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :require_login, except: [:index, :show]
  include ProjectsHelper

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.save
    redirect_to project_path(@project)
    flash[:notice] = "'#{@project.projectname}' Created"
  end
  
  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to project_path(@project)
    flash[:notice] = "'#{@project.projectname}' Updated"
  end

  def destroy
    @project = Project.find(params[:id])
    flash[:notice] = "'#{@project.projectname}' Deleted"
    @project.destroy
    redirect_to projects_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/contactforms_helper.rb
module ContactformsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def project_params
		params.require(:project).permit(:projectname, :projectdescription, :projectdetails, :image, :preview)
	end
end

app/views/author_sessions/new.html.erb
<div class="formpage">
<h1>Login</h1>

<%= form_tag author_sessions_path, method: :post do %>

<div class="form">
    <%= label_tag :email %><br>
    <%= text_field_tag :email %>
</div>

<div class="form">
    <%= label_tag :password %><br>
    <%= password_field_tag :password %>
</div>

  <div class="form">
    <%= submit_tag "Login" %>
  </div>
  <% end -%>

<%= link_to 'Back', projects_path, :class => "admin" %>
</div>

app/views/authors/_form.html.erb
<div class="formpage">
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="form">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="form">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="form">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="form">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author, :class => "admin" %> |
<%= link_to 'Back', authors_path, :class => "admin" %>

app/views/authors/index.html.erb
<h1>Listing Authors</h1>

<table>
  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author, :class => "admin"  %> | </td>
        <td> <%= link_to 'Edit', edit_author_path(author), :class => "admin"  %> | </td>
        <td> <%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' }, :class => "admin"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path, :class => "admin"  %> | 
<%= link_to 'Portfolio', projects_path , :class => "admin"  %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path, :class => "admin" %>

app/views/authors/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<%= link_to 'Edit', edit_author_path(@author), :class => "admin"  %> |
<%= link_to 'Back', authors_path , :class => "admin" %>

app/views/contacts/create.html.erb
<div class="formpage">
	<h1> Thank you for your message!</h1>
	<p> I'll get back to you soon! </p>
</div>

app/views/contacts/new.html.erb
<div id="form-main" class="cf">
  	<div id="form-div" class="cf">
	<%= form_for(@contact) do |f|  %>
	   <p class="name">
	  <%= f.text_field :name, required: true, :placeholder => "Your Name", :class => "validate[required,custom[onlyLetter],length[0,100]] feedback-input", :id => "name" %>
	  </p>

	  <p class="email">
	  <%= f.email_field :email, required: true, :placeholder => "Your Email", :class => "validate[required,custom[email]] feedback-input", :id => "email"  %>
	  </p>

	  <p class="text">
	  <%= f.text_area :message, as: :text, :class => "validate[required,length[6,300]] feedback-input", :id => "comment" %>
	  </p>
	
	  <div class="hidden">
	  <%= f.label :nickname %><br/>
	  <%= f.text_field :nickname, hint: "Leave this blank - spam filter" %>
	  </div>
	
	  <div class="submit">
	    <%= f.submit "Send Message", :id => "button-blue" %>
	    <div class="ease"></div>
	  </div>
	<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simon's Portfolio</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
</head>
<body>

<div style="position: absolute; visibility: hidden" id="notice"><%= notice %></div>
<div id="ohsnap"></div>

<header>
	<nav class="effect">
		<ul id="menu">
			<li><%= link_to("About", about_path, :class => "effect") %></li>
			<li><%= link_to("Projects", projects_path, :class => "effect") %></li>
			<li><a class="effect" href="https://www.visualcv.com/simon-somlai" target="_blank">Resumé</a></li>
			<li><%= link_to("Contact", new_contact_path, :class => "effect") %></li>
		</ul>
	</nav>
</header>

<div class="container">
<%= yield %>
</div>

<footer> 
	<ul>
		<li><a href="https://twitter.com/BasicGrowth">Twitter</a></li> | 
		<li><a href="https://www.linkedin.com/in/simon-somlai-27a4648a?trk=nav_responsive_tab_profile_pic">LinkedIn</a></li> | 
		<li><a href="https://github.com/SimonSomlai">GitHub</a></li> |
		<li><%= link_to("Contact", new_contact_path) %></a></li>
	</ul>
	<p> 
		<% if logged_in? %>
		<%= current_user.username %> |
		<%= link_to "Logout", logout_path %>
		<% end -%>
	</p>
	
 </footer>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/pages/about.html.erb
<div class="aboutpage">
<section class="head">
<div class="slider">
      <ul>
        <li><img src="<%= asset_path('design1.jpg') %>"/></li>
        <li><img src="<%= asset_path('design2.jpg') %>"/></li>
        <li><img src="<%= asset_path('design3.jpg') %>"/></li>
        <li><img src="<%= asset_path('design4.jpg') %>"/></li>
        <li><img src="<%= asset_path('design5.jpg') %>"/></li>
      </ul>
    </div>
<div class="heading">
<h2>Simon Somlai</h2>
<h4>Web Developer & Writer<h4>
<hr class="dividertop"/>
<a href="#"><img class="downarrow" src="<%= asset_path('downarrow.png') %>"/></a>
</div>
</section>

<section class="about cf">
  <div class="bio fadeIn">
    <h3>Who Am I ?</h3>
    <img src="<%= asset_path('bio.JPG') %>"/>
    <h5> Simon Somlai </h5>
    <div class="slider">
      <ul>
        <li><strong>Strengths: </strong> Analytical Thinking, Organizing Data, Creating Systems, Problem-Solving, Planning, Independent Work</li>
        <li><strong>Interests: </strong> Health, Self-Improvement, Writing, Psychology, Astronomy, Technology, Science-Fiction/Fantasy</li>
        <li><strong>Hobbies: </strong> Lifting Heavy Things, Reading Books, Strategic Board Games, Blogging, Eating A Lot</li>
      </ul>
    </div>
  </div>

  <div class="skills fadeIn">
    <h3>How Do I Work ?</h3>
    <img class="html" src="<%= asset_path('html.png') %>"/>
    <img class="css" src="<%= asset_path('css.png') %>"/>
    <img class="js" src="<%= asset_path('js.png') %>"/>
    <img class="ruby" src="<%= asset_path('ruby.png') %>"/>
  </div>
</section>

<hr class="divider"/>

<section class="services">
  <h3> How Can I Help ?</h3>
  <div class="serviceoptions fadeIn">
  <ul class="serviceoptionslist">
    <li><a class="psd" href="#">PSD To HTML/CSS</a>
      <ul>
        <li>W3C Validated</li>
        <li>Responsive Layout</li>
        <li>Background Video/Slider/Carousel</li>
      </ul>
    </li>

    <li><a class="land" href="#">Create Landing Pages</a>
    <ul>
        <li>W3C Validated</li>
        <li>Responsive Layout</li>
        <li>Background Video/Slider/Carousel</li>
        <li>Custom Forms</li>
        <li>Aweber/Mailchimp Integration</li>
      </ul>
    </li>

    <li><a class="app" href="#">Build Web Applications</a>
    <ul>
        <li>Ruby On Rails Application</li>
        <li>Login Function</li>
        <li>Content Management Page</li>
        <li>Forms Delivered To Email</li>
      </ul>
    </li>
  </ul>
</div>
  <div class="serviceimages fadeIn">
    <img class="psd" src="<%= asset_path('psd.png') %>"/>
    <img class="land" src="<%= asset_path('land.png') %>"/>
    <img class="app" src="<%= asset_path('app.png') %>"/>
  </div>
</section>

<hr class="divider"/>

<section class="contact fadeIn">
  <a href="<%= new_contact_path %>" class="button red">Contact Me! ♥</a>
</section>
</div>

app/views/projects/_form.html.erb
<%= form_for @project, html: {multipart: true} do |f| %>
  <div class="form">
  <%= f.label :projectname, "Project Name" %>
  <%= f.text_field :projectname %>
  </div>

  <div class="form">
  <%= f.label :projectdetails, "Project Summary" %>
  <%= f.text_field :projectdetails %>
  </div>

  <div class="formeditor">
  <%= f.label :projectdescription, "Project Description" %>
  <%= f.text_area :projectdescription %>
  </div>

  <div class="form">
  <%= f.label :image, "Header Image" %>
  <%= f.file_field :image %>
  </div>

  <div class="form">
  <%= f.label :preview, "Preview Image" %>
  <%= f.file_field :preview %>
  </div>

  <div class="form">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="formpage">
<h1>Editing Project</h1>

<%= render 'form' %>
<%= javascript_include_tag "//cdn.tinymce.com/4/tinymce.min.js" %>
<script>tinymce.init({ selector:'textarea' });</script>

<%= link_to 'Show', @project, :class => "admin" %> |
<%= link_to 'Back', projects_path, :class => "admin"  %>
</div>

app/views/projects/index.html.erb
<div class="index">
<% @projects.each do |project|  %>
  <ul class="projectindex">

  <% if logged_in? %>
    <li class="admin"><%= link_to 'Edit', edit_project_path(project) %></li> |
  <li class="admin"><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <% end %>

    <li><%= link_to image_tag(project.image.url), project %></li>
    <li>
      <h2 class="bottom title"> <%= link_to project.projectname, project %></h2>
      <h3 class="bottom details">~ <%= project.projectdetails %> ~</h3>
    </li>
    
  </ul>
    <% end %>
<br/>

  <% if logged_in? %>
  <%= link_to 'New Project', new_project_path, :class => "admin" %> 
  <% end %>

</div>

app/views/projects/new.html.erb
<div class="formpage">
<h1>New Project</h1>

<%= render 'form' %>
<%= javascript_include_tag "//cdn.tinymce.com/4/tinymce.min.js" %>
<script>tinymce.init({ selector:'textarea' });</script>

<%= link_to 'Back', projects_path, :class => "admin" %>
</div>

app/views/projects/show.html.erb
<div class="projectshow cf">
	<h1>
	<%= @project.projectname %> 
	</h1>
	<a href="<%= @project.preview.url %>" data-lightbox="<%= @project.projectname %>"><%= image_tag(@project.preview.url :medium) %></a>
	<div class="description">
	<p><%= raw(@project.projectdescription) %> </p>
	<a class="viewproject" href="<%= asset_path(@project.projectname) %>">See Project</a>
	</div>


<% if logged_in? %>
<%= link_to 'Edit', edit_project_path(@project), :class => "admin" %> |
<%= link_to 'Back', projects_path, :class => "admin" %> 
<% end %>

</div>
<br/>


 